open "lastcall.txt" for output as #1
print #1,chr$(2)
print #1,chr$(1);"10               ษอออออออออออออออออออออออออออออออออออออออออออป"
print #1,"                  บ         The Boss Last Caller Log          บ"
print #1,"                  ศอออออออออออออออออออออออออออออออออออออออออออผ"
print #1,chr$(1)"14                                 ";date$
print #1,"ฤฤฤฤฤฤยฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤยฤฤฤฤฤฤฤฤฤฤฤฤยฤฤฤฤฤฤฤฤฤฤฤฤฤฤยฤฤฤฤฤฤฤฤฤฤฤยฤฤฤฤฤฤฤฤ"
print #1,"      ณ Caller's Name         ณ Login Time ณ Logout Time  ณ Baud Rate ณ"
print #1,"ฤฤฤฤฤฤมฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤมฤฤฤฤฤฤฤฤฤฤฤฤมฤฤฤฤฤฤฤฤฤฤฤฤฤฤมฤฤฤฤฤฤฤฤฤฤฤมฤฤฤฤฤฤฤฤ"
print #1,chr$(1)"11"
close #1


