
10                     иммммммммммммммммммммммм╩
                        ╨  BOSS BULLETIN BOARD  ╨
                        хммммммммммммммммммммммм╪
11             зддддддддддддддддддддддддддддддддддддддд©
                Ё [M]essage Area        [P]age Sysop    Ё
                Ё [C]omment To SysOp    [U]ser Stats    Ё
                Ё [A]lter Stats         [B]ulletins     Ё
                Ё [L]ist Users          [O]n-Line Games Ё
                Ё [F]ile Areas          [G]ood Bye!     Ё
                Ё [Y] Ansi Chat         [S]hell To Dos  Ё
                Ё [Q]wik bbs list       [N]ew E-Mail    Ё
                Ё [R]ead Lost Mail                      Ё
                юддддддддддддддддддддддддддддддддддддддды
14           зддддддддддддддддддддддддддддддддддддддддддд©
              Ё    S U P E R    U S E R   A C C E S S     Ё
              юддддддддддддддддддддддддддддддддддддддддддды
12              Enter Command <Main Menu>
